name: MGSM2Fix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4

    - name: Download ASI Loader x64
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader_x64.zip"
    - run: mkdir .\asiloader
    - run: unzip Ultimate-ASI-Loader_x64.zip -d .\asiloader
    - run: mv .\asiloader\dinput8.dll .\asiloader\d3d11.dll

    - name: Download ASI Loader x86
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader.zip"
    - run: unzip Ultimate-ASI-Loader.zip -d .\asiloader

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\M2Package.bat

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MGSM2Fix-run-${{ github.run_number }}
        path: dist/
