name: MGSM2Fix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\M2Package.bat

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MGSM2Fix
        path: MGSM2Fix.zip
